<!-- BEGIN (write your solution here) -->
<div>Создание курса</div>
<form action="/courses" method="post">
    <label>
        Название
        <input name="course[title]" value="<?= (isset($course['title'])) ? $course['title'] : '' ?>">
        <?php if (isset($errors['title'])): ?>
        <div><?= $errors['title'] ?> </div>
        <?php endif; ?>
    </label>
    <label>
        Платность
        <select name="course[paid]">
            <option value="-1">Выберите</option>
            <option <?= isset($course['paid']) && $course['paid'] === "1" ? 'selected' : '' ?> value="1">Платный</option>
            <option <?= isset($course['paid']) && $course['paid'] === "0" ? 'selected' : '' ?> value="0">Бесплатный</option>
        </select>
        <?php if (isset($errors['paid'])): ?>
        <div><?= $errors['paid'] ?> </div>
        <?php endif; ?>
    </label>
    <input type="submit" value="Create it!">
</form>
<!-- END -->
